### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#430]
Add a method to reset password when password is forgotten at login or to change it in the settings. May split this into two issues. The priority is resetting when password is forgotten.

**Comment by dmitrizagidulin** [comment]
@kayaelle - So, the problem with this functionality is that, although it's really convenient, it's not really possible. The database of credentials and keys is /encrypted/ with the user's password. 
If this was a custodial wallet, then DCC would store a copy of the encryption key on our servers, and use /that/ for password reset. Since this is non-custodial, the key never leaves the user's phone, and it's not possible to reset.

**Comment by kayaelle** [comment]
Closing based on @dmitrizagidulin comment above.
